#!/bin/sh

function listener {
    eww logs | while read -r line; do decorate_windows "$line"; done
}

# bspc rule -a "eww-music" state=floating layer=below &
bspc rule -a "eww-music" state=floating layer=above  &
bspc rule -a "eww-bar" state=floating layer=above  &
eww kill ; eww open bar && eww update "HOME=$HOME" &
# eww open music &

